services:
  mongo:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mongo
    ports:
      - "9196:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - GLIBC_TUNABLES=${GLIBC_TUNABLES}
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/dev:/docker-entrypoint-initdb.d/data-stage:ro
      - mongo_data:/data/db

volumes:
  mongo_data:
